### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by Mte90** [mozilla/mozilla-presentation-templates#21]
I made year ago a fork that I continue to update on https://github.com/Mte90/Mozilla-Presentation-Boilerplate.
The readme contain the list of difference from the original version of shower and also of this and the demo is on https://mte90.github.io/Mozilla-Presentation-Boilerplate/
Maybe it is time to switch on my version or mix it?

**Comment by codepo8** [comment]
Fine by me :)

**Comment by Mte90** [comment]
Someone can assign to me this? i can forget without that XD

**Comment by Mte90** [comment]
Ok I updated my slides with the new mozilla design but my repo is not anymore a fork of this so I cannot create a PR.

https://mte90.github.io/Mozilla-Presentation-Boilerplate/

**Comment by juj** [comment]
Hey, since the new _"m://a"_ branding and styling, (https://mozilla.ninja/visualelements), I wonder if that has come with updated presentation template recommendations, or would people be preferred to go with the existing ones?

**Comment by Mte90** [comment]
My boilerplate needs an update too for the new stile guide but as I can see looking on presentation made by Mozilla employee they are using different design for them

**Comment by emceeaich** [comment]
I've filed https://bugzilla.mozilla.org/show_bug.cgi?id=1433749 for the obsolete content on https://www.mozilla.org/en-US/styleguide/

**Comment by Mte90** [comment]
Good point!
I need to update again the slides with the new design.
