### ISSUE TITLE
HTML slideshows cannot be exported to PDF

### ISSUE THREAD

**Issue by fabi1cazenave** [mozilla/mozilla-presentation-templates#7]
The HTML template is based on [shower](http://shwr.me/), which [prints just fine in Chrome or wkhtmltopdf](https://github.com/shower/shower/wiki/Print): every slide is printed on one page, which makes it straight-forward to export an HTML slideshow to PDF.

Unfortunately, this custom Mozilla theme does not seem to support it: the “one slide per page” stylesheet is never activated. Maybe I’m doing it wrong?

**Comment by Mte90** [comment]
I've created a new version of this template based on the new shower version with the mozilla theme https://github.com/Mte90/Mozilla-Presentation-Boilerplate
